// <auto-generated />
using System;
using McGreggorFinancials.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace McGreggorFinancials.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200108011006_Crypto")]
    partial class Crypto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("McGreggorFinancials.Models.Accounts.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<string>("Description");

                    b.Property<int>("TargetID");

                    b.Property<int>("TypeID");

                    b.HasKey("ID");

                    b.HasIndex("TargetID");

                    b.HasIndex("TypeID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Accounts.AccountType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("AccountTypes");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Crypto.Coin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CryptoCurrencyID");

                    b.Property<DateTime>("Date");

                    b.Property<int>("NumOfCoins");

                    b.Property<double>("PurchasePrice");

                    b.HasKey("ID");

                    b.HasIndex("CryptoCurrencyID");

                    b.ToTable("Coins");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Crypto.CryptoCurrency", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Ticker")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("CryptoCurrencies");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Donations.Charity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Charities");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Donations.Donation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<int>("CharityID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("PaymentMethodID");

                    b.HasKey("ID");

                    b.HasIndex("CharityID");

                    b.HasIndex("PaymentMethodID");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Expenses.CreditBalance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<int>("PaymentMethodID");

                    b.HasKey("ID");

                    b.HasIndex("PaymentMethodID")
                        .IsUnique();

                    b.ToTable("CreditBalance");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Expenses.Expense", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("ExpenseCategoryID");

                    b.Property<int>("PaymentMethodID");

                    b.HasKey("ID");

                    b.HasIndex("ExpenseCategoryID");

                    b.HasIndex("PaymentMethodID");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Expenses.ExpenseCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Expenses.PaymentMethod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCredit");

                    b.Property<string>("Method")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Income.IncomeCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("IncomeCategories");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Income.IncomeEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<int>("CategoryID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("IncomeEntries");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Stocks.Sector", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Stocks.Share", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("NumOfShares");

                    b.Property<double>("PurchasePrice");

                    b.Property<int>("StockID");

                    b.HasKey("ID");

                    b.HasIndex("StockID");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Stocks.Stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .IsRequired();

                    b.Property<int>("SectorID");

                    b.Property<string>("Ticker")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("SectorID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Targets.TargetAmount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int>("Percentage");

                    b.Property<int>("TypeID");

                    b.HasKey("ID");

                    b.HasIndex("TypeID");

                    b.ToTable("TargetAmounts");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Targets.TargetType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("TargetTypes");
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Accounts.Account", b =>
                {
                    b.HasOne("McGreggorFinancials.Models.Targets.TargetAmount", "TargetAmount")
                        .WithMany()
                        .HasForeignKey("TargetID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("McGreggorFinancials.Models.Accounts.AccountType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Crypto.Coin", b =>
                {
                    b.HasOne("McGreggorFinancials.Models.Crypto.CryptoCurrency", "CryptoCurrency")
                        .WithMany()
                        .HasForeignKey("CryptoCurrencyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Donations.Donation", b =>
                {
                    b.HasOne("McGreggorFinancials.Models.Donations.Charity", "Charity")
                        .WithMany()
                        .HasForeignKey("CharityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("McGreggorFinancials.Models.Expenses.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Expenses.CreditBalance", b =>
                {
                    b.HasOne("McGreggorFinancials.Models.Expenses.PaymentMethod", "PaymentMethod")
                        .WithOne("CreditBalance")
                        .HasForeignKey("McGreggorFinancials.Models.Expenses.CreditBalance", "PaymentMethodID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Expenses.Expense", b =>
                {
                    b.HasOne("McGreggorFinancials.Models.Expenses.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("McGreggorFinancials.Models.Expenses.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Income.IncomeEntry", b =>
                {
                    b.HasOne("McGreggorFinancials.Models.Income.IncomeCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Stocks.Share", b =>
                {
                    b.HasOne("McGreggorFinancials.Models.Stocks.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Stocks.Stock", b =>
                {
                    b.HasOne("McGreggorFinancials.Models.Stocks.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("McGreggorFinancials.Models.Targets.TargetAmount", b =>
                {
                    b.HasOne("McGreggorFinancials.Models.Targets.TargetType", "TargetType")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
